doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        server_version: '13'
        charset: utf8
        types:
          uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
          datetime_immutable: App\Shared\Infrastructure\Persistence\Doctrine\Types\DateTimeType
          email: App\Shared\Infrastructure\Persistence\Doctrine\Types\EmailType
          hashed_password: App\Shared\Infrastructure\Persistence\Doctrine\Types\HashedPasswordType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/packages/doctrine/mapping/user'
                prefix: 'App\User'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
