doctrine_migrations:
    enable_profiler: '%kernel.debug%'
    migrations_paths:
        App\Shared\Infrastructure\Persistence\Doctrine\Migrations: '%kernel.project_dir%/src/App/Shared/Infrastructure/Persistence/Doctrine/Migrations'