executor-machine: &executor-machine "ubuntu-2004:202111-02"

version: 2
jobs:
  build:
    machine:
      image: *executor-machine
      docker_layer_caching: true

    steps:
      - checkout

      - attach_workspace:
          at: ~/
      - run:
          name: Change owner on project dir (docker needs uid 1000, circleci can be another uid)
          command: sudo chown -R 1000:1000 ../project
      - run:
          name: Pull docker images 
          command: docker-compose pull api nginx
      - run:
          name: Start container
          command: APP_ENV=test CONTAINERS='api nginx' make up
      - run:
          name: Prepare api
          command: |
            make vendor
            make cache
      - run:
          name: Run tests
          command:  APP_ENV=test make test
    # steps:
    #   - checkout

    #   - run: php --version
    #   - run: sudo apt update
    #   - run: sudo docker-php-ext-install zip

    #   - restore_cache:
    #       keys:
    #         - v1-dependencies-{{ checksum "composer.json" }}
    #         - v1-dependencies-

    #   - run:
    #       name: "Create Environment file"
    #       command: mv .env.test .env

    #   - run:
    #       name: "Install Dependencies"
    #       command: composer install -n --prefer-dist

    #   - save_cache:
    #       key: v1-dependencies-{{ checksum "composer.json" }}
    #       paths:
    #         - ./vendor
    #   - run:
    #       name: Run web server
    #       command: php bin/console server:run
    #       background: true

    #   # run Behat test
    #   - run:
    #       name: "Run Behat test"
    #       command: vendor/bin/behat
