# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    exception_to_status:
        InvalidArgumentException: 400
        App\User\Domain\Exception\InvalidCredentialsException: 401
        App\User\Domain\Exception\ForbiddenException: 403
        App\Shared\Infrastructure\Persistence\ReadModel\Exception\NotFoundException: 404
        Broadway\Repository\AggregateNotFoundException: 404

services:
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
          public: true
          tags:
            - { name: messenger.message_handler, bus: messenger.bus.command }

   

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App/*'
        exclude: '../src/App/**/{Migrations,EventSubscriber}'
    
    UI\:
        resource: '../src/UI/*'
        exclude: '../src/UI/**/{EventSubscriber}'


    Core\Shared\Infrastructure\Bus\Command\MessengerCommandBus:
        arguments:
          - '@messenger.bus.command'

    UI\Http\Rest\Controller\:
        resource: '../src/UI/Http/Rest/Controller/*'
        tags: [ 'controller.service_arguments' ]

    UI\Http\Rest\EventSubscriber\JsonBodyParserSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 100 }


    